article_top_news:
     path:     /top-news
     defaults: { _controller: WebFrontBundle:Article:topNews }

article_recherche:
     path:     /recherche
     defaults: { _controller: WebFrontBundle:Article:rechercheArticle }
article_hastag:
     path:     /hastag/{key}
     defaults: { _controller: WebFrontBundle:Article:hastag, key: null }


