homepage:
     path:     /{_locale}
     defaults: { _controller: WebFrontBundle:HomePage:index, _locale:%locale% }
     requirements:
        _locale: en|fr

   
topnews:
     path:    /top-news
     defaults: { _controller: WebFrontBundle:HomePage:topNews }


pluslus:
     path:    /plus-lus
     defaults: { _controller: WebFrontBundle:HomePage:plusLus }     


actualitesporitifs:
     path:    /actualite-sportif
     defaults: { _controller: WebFrontBundle:HomePage:actualiteSportif }


actualites_link:     
     path:    /actualites/{cat}
     defaults: { _controller:WebFrontBundle:HomePage:actualitesCategorie }

