<?php

namespace Web\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentDetailsRepository extends EntityRepository
{
	public function findByOptions($options)
	{
		$query = $this->createQueryBuilder("p");
		
		if(isset($options['dateDu'])){
			$query->andWhere("p.createdAt <= :date_du")
			->setParameter("date_du", new \DateTime($options['dateDu']));
		}
		
		if(isset($options['dateAu'])){
			$query->andWhere("p.createdAt >= :date_au")
			->setParameter("date_au", new \DateTime($options['dateAu']));
		}
		
		return $query->getQuery()->getResult();
	}
}
