<?php

namespace App\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FluxRssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRssRepository extends EntityRepository
{
    /**
     * Find all FluxRSS entities
     *
     * @return array
     */
    public function findAll()
    {
        return $this->findBy(array());
    }
}
